# Generated by Django 5.0.6 on 2024-08-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookresult',
            fields=[
                ('rollno', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('regno', models.CharField(default='2021-UOK-04201', max_length=23)),
                ('sname', models.CharField(default='', max_length=39)),
                ('fname', models.CharField(default='', max_length=50)),
                ('session', models.CharField(default='BS Software Engineering Fall (2021-2025)', max_length=50)),
                ('semester', models.CharField(default='Spring 2023 4th Semester', max_length=49)),
                ('courdecode', models.CharField(default='SE-3101', max_length=34)),
                ('crhours', models.IntegerField(default=4)),
                ('lettergrage', models.CharField(default='A', max_length=34)),
                ('bname', models.CharField(default='Web Engineering', max_length=199)),
                ('tmark', models.IntegerField(default=200)),
                ('omark', models.IntegerField(default=145)),
                ('percentage', models.FloatField(default=50.0)),
                ('courdecode1', models.CharField(default='SE-3106', max_length=34)),
                ('crhours1', models.IntegerField(default=4)),
                ('lettergrage1', models.CharField(default='A', max_length=34)),
                ('bname1', models.CharField(default='Professional Practices', max_length=199)),
                ('tmark1', models.IntegerField(default=200)),
                ('omark1', models.IntegerField(default=145)),
                ('percentage1', models.FloatField(default=50.0)),
                ('courdecode2', models.CharField(default='CS-3102', max_length=34)),
                ('crhours2', models.IntegerField(default=4)),
                ('lettergrage2', models.CharField(default='A', max_length=34)),
                ('bname2', models.CharField(default='Information Security', max_length=199)),
                ('tmark2', models.IntegerField(default=200)),
                ('omark2', models.IntegerField(default=145)),
                ('percentage2', models.FloatField(default=50.0)),
                ('courdecode3', models.CharField(default='SE-3104', max_length=34)),
                ('crhours3', models.IntegerField(default=4)),
                ('lettergrage3', models.CharField(default='A', max_length=34)),
                ('bname3', models.CharField(default='Software Quality Engineering', max_length=199)),
                ('tmark3', models.IntegerField(default=200)),
                ('omark3', models.IntegerField(default=145)),
                ('percentage3', models.FloatField(default=50.0)),
                ('courdecode4', models.CharField(default='EG-3103', max_length=34)),
                ('crhours4', models.IntegerField(default=4)),
                ('lettergrage4', models.CharField(default='A', max_length=34)),
                ('bname4', models.CharField(default='Machine Learning', max_length=199)),
                ('tmark4', models.IntegerField(default=200)),
                ('omark4', models.IntegerField(default=145)),
                ('percentage4', models.FloatField(default=50.0)),
                ('courdecode5', models.CharField(default='CS-3102', max_length=34)),
                ('crhours5', models.IntegerField(default=4)),
                ('lettergrage5', models.CharField(default='A', max_length=34)),
                ('bname5', models.CharField(default='Human Resource Management', max_length=199)),
                ('tmark5', models.IntegerField(default=200)),
                ('omark5', models.IntegerField(default=145)),
                ('percentage5', models.FloatField(default=50.0)),
                ('gpa', models.FloatField(default=3.0)),
                ('remarks', models.CharField(default='Promoted', max_length=34)),
            ],
        ),
    ]
